command: [
  "reflex", 
  "run",
  "--env",
  "prod",
  "--single-port",
  "--frontend-port",
  "$DATABRICKS_APP_PORT"
]

env:
  - name: "HOME"
    value: "/tmp/reflex"
  - name: "REFLEX_SHOW_BUILT_WITH_REFLEX"
    value: 0
