command: [
  "reflex", 
  "run",
  "--env",
  "prod",
  "--single-port",
  "$DATABRICKS_APP_PORT"
]

env:
  - name: "HOME"
    value: "/tmp/reflex"
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "e8cd4b9d069bc806"
  - name: "DATABRICKS_CATALOG"
    value: "practice_tom"
  - name: "DATABRICKS_SCHEMA"
    value: "public"
  - name: "REFLEX_SHOW_BUILT_WITH_REFLEX"
    value: 0